#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger:
  - main

schedules:
  - cron: '30 0,9,12 * * MON,TUE,WED,THU,FRI'
    displayName: M-F 06:00, 15:00 and 18:00 (UTC + 5:30) India daily build
    always: true
    branches:
      include:
        - main

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)]
  DEBIAN_FRONTEND: noninteractive
  LinuxContainerImage: mcr.microsoft.com/onebranch/cbl-mariner/build:2.0

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
    - repository: qdl-template
      type: git
      name: "Nuance Enterprise/sample-quality-gates-repo"
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault:
      enabled: true
      runmode: stage
      uploadToPipelineArtifacts: false
      dependsOn:
        - cloud_test_upload_stage
      artifacts:
        - drop_cloud_test_upload_stage_cloud_test_upload_job
    globalSdl: # https://aka.ms/obpipelines/sdl
      runmode: stage
      tsa:
        enabled: false
      policheck:
        break: true
      codeql:
        compiled:
          enabled: true
    stages:
      - template: common_official.yml@self
        parameters:
          isOfficial: "true"
          useGitVersion: "true"
